### ISSUE TITLE
Consistent 500 error

### ISSUE THREAD

**Issue by ianb** [google/generative-ai-docs#211] opened 2023-12-31 18:58 UTC
### Description of the bug:

I get lots of intermittent 500 errors (lots and lots!) but this request gives consistent 500 errors:

```json
{"contents":
  [
    {"role":"user","parts":[{"text":""},{"text":""}]}
  ],
  "tools":[{"functionDeclarations":[{"name":"locationFamilyInfo","description":"Identify the status/classes of people in Mycenae in 1200BC.","parameters":{"type":"object","properties":{"classes":{"type":"array","items":{"type":"string","description":"A list of classes or status of people in the location, such as \"upper class\", \"surf\", \"untouchable\", etc. Include some exceptional classes, such as \"royalty\", \"nobility\", \"priesthood\", \"warrior\", etc. Give the full range of classes/status in society at the time."}},"ethnicities":{"type":"array","items":{"type":"string","description":"A list of races and ethnicities in the location, such as \"white\", \"hispanic\", \"Hmong\", etc."}},"religions":{"type":"array","items":{"type":"string","description":"A list of religions in the location, such as \"Christian\", \"Muslim\", \"Hindu\", etc. Can include denominations, such as \"Catholic\", \"Protestant\", \"Sunni\", \"Shia\", etc."}}},"required":["classes","ethnicities","religions"]}}]}],
  "generationConfig":{"temperature":0.5}
}
```

Notably the request text is weird. GPT answers this successfully and accurately based on the function call alone.

### Actual vs expected behavior:

No 500 error

**Comment by kpripper** [comment] 2024-01-01 14:58
I have the same problem. Approximately half of the requests give an error of 500. The frequency of requests is 2 per minute. No more than 1,000 tokens per prompt.

**Comment by davidstackio** [comment] 2024-01-03 21:58
In the last few days I've also been getting more 500 errors as well (beyond the usual SAFETY errors). I'm using the [JavaScript SDK](https://github.com/google/generative-ai-js) in Node v18.19.0.

My error is:
```
GoogleGenerativeAIError: [500 Internal Server Error] An internal error has occurred. Please retry or report in
https://developers.generativeai.google/guide/troubleshooting
```

Which brought me here.

**Comment by kpripper** [comment] 2024-01-04 07:37
Do you use simultaneous requests with different API keys from one IP address?

**Comment by davidstackio** [comment] 2024-01-04 17:31
@kpripper I do not. I just have one API key from one domain.

**Comment by MarkDaoust** [comment] 2024-01-11 18:43
Hi, everyone. Yes, the service was having capacity issues recently. This should be running better now.

**Comment by keertk** [comment] 2024-01-18 00:09
Closing this issue since it's been resolved, but please feel free to reopen or raise a new issue if you see this again.

**Closed by keertk** 2024-01-18 00:09 UTC
Labels: type:bug

**Comment by shaayaansh** [comment] 2024-02-06 05:15
I'm getting this error in the past week. I'm using colab and just one API. This is how I initialized my model:
```
safety_settings = [{
  "category": "HARM_CATEGORY_HARASSMENT",
  "threshold": "HIGH"
},
{"category": "HARM_CATEGORY_HATE_SPEECH",
 "threshold": "BLOCK_NONE"}]

model = genai.GenerativeModel('gemini-pro', safety_settings=safety_settings)
```

I'm running the following code in a for loop and none of my inputs exceed 1000 tokens. The error occurs sometimes after 150 iterations and some times after the first 10. I don't understand whats happening.

```
   response = model.generate_content(prompt.format(sent),
                                      generation_config=genai.types.GenerationConfig(
                                          candidate_count=1, max_output_tokens=10,
                                          temperature=1.0))
```

**Comment by 1andDone** [comment] 2024-02-26 12:19
Seeing the same error on my end. Is the solution to just wrap the request in a retry?

**Comment by deathemperor** [comment] 2024-04-29 01:48
Is the capacity issue happening again? Been getting 500 for all request for more than 24 hours now

**Comment by MarkDaoust** [comment] 2024-04-29 14:58
I don't see all the internal struggles. It could be that, just be sure to try a vanilla request to rule out some bad input causing it to fail.

**Comment by deathemperor** [comment] 2024-05-02 02:38
> I don't see all the internal struggles. It could be that, just be sure to try a vanilla request to rule out some bad input causing it to fail.

it is a vanilla request taken from https://cloud.google.com/nodejs/docs/reference/vertexai/latest

the sample source

```js
const {
  FunctionDeclarationSchemaType,
  HarmBlockThreshold,
  HarmCategory,
  VertexAI,
} = require("@google-cloud/vertexai");

const project = "careportal-357509";
const location = "us-central1";
const textModel = "gemini-1.0-pro";
const visionModel = "gemini-1.0-pro-vision";

const vertexAI = new VertexAI({ project: project, location: location });

// Instantiate Gemini models
const generativeModel = vertexAI.getGenerativeModel({
  model: textModel,
  // The following parameters are optional
  // They can also be passed to individual content generation requests
  safetySettings: [
    {
      category: HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT,
      threshold: HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE,
    },
  ],
  generationConfig: {
    maxOutputTokens: 256,
    responseMimeType: "application/json",
  },
});

const generativeVisionModel = vertexAI.getGenerativeModel({
  model: visionModel,
});

const generativeModelPreview = vertexAI.preview.getGenerativeModel({
  model: textModel,
});

async function generateContent() {
  const request = {
    contents: [{ role: "user", parts: [{ text: "How are you doing today?" }] }],
  };
  const result = await generativeModel.generateContent(request);
  const response = result.response;
  console.log("Response: ", JSON.stringify(response));
}

generateContent();
```

**Comment by deathemperor** [comment] 2024-05-02 02:42
Just tried to make it really `vanilla` by removing `responseMimeType: "application/json",` and it works. It's not like this 5 days ago.

I know `responseMimeType: "application/json",` is not supported in JS sdk but still tried it and it worked which helped my application. Now suddenly it doesn't and my application stopped working.

**Comment by deathemperor** [comment] 2024-05-02 02:53
Issue mentioned at https://github.com/googleapis/nodejs-vertexai/issues/306

**Comment by MarkDaoust** [comment] 2024-05-02 17:21
For @ianb 

Yeah, it looks like it fails if there's no input:

```
model.generate_content(
  contents=[{"role":"user","parts":[{"text":""}]}],
)
```

**Comment by MarkDaoust** [comment] 2024-05-02 17:28
@deathemperor 

Errors may be different between us and vertex. Are you able to reproduce this with `google.generativeai`? This seems to work fine:

```
model = genai.GenerativeModel('gemini-1.5-pro-latest')

model.generate_content(
  contents="How are you doing today?",
  generation_config={'response_mime_type':'application/json'}
)

response.text #  '{\n\n"response": "I am an AI language model, so I do not have feelings or experiences like humans do. However, I am here to assist you with any questions or tasks you may have." \n\n}\n\n'
```

**Comment by deathemperor** [comment] 2024-05-03 05:15
I'm using nodejs sdk, tried with `gemini-1.5-pro-preview-0409` (`gemini-1.5-pro-latest` throws Publisher Model not found for me) doesn't work.

**Comment by deathemperor** [comment] 2024-05-09 02:34
After submitting a support ticket with GCP, I checked again today and the 500 error is gone.
